version: 2.1
jobs:

  build-deploy:
    executor: nagios
    parameters:
      version:
        type: string
      latest:
        type: string
        default: "false"
    steps:
      - core:
          version: << parameters.version >>
      - core-web:
          version: << parameters.version >>
      - core-web-plugins:
          version: << parameters.version >>
          latest: << parameters.latest >>

executors:
  nagios:
    docker:
      - image: circleci/node:10

commands:
  common:
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.06.1-ce"
            sudo curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            sudo tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            sudo mv /tmp/docker/* /usr/bin
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  core:
    parameters:
      version:
        type: string
    steps:
      - common
      - run:
          name: Nagios Core
          command: |
            echo "Building Nagios << parameters.version >> - Core"
            docker build --build-arg VERSION=<< parameters.version >> -t remie/docker-nagios:<< parameters.version >>-core ./core/Dockerfile
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker push remie/docker-nagios:<< parameters.version >>-core
            fi

  core-web:
    parameters:
      version:
        type: string
    steps:
      - common
      - run:
          name: Nagios Core+Web
          command: |
            echo "Building for Nagios << parameters.version >> - Core + Web UI"
            docker build --build-arg VERSION=<< parameters.version >> -t remie/docker-nagios:<< parameters.version >>-core-web ./core-web/Dockerfile
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker push remie/docker-nagios:<< parameters.version >>-core-web
            fi

  core-web-plugins:
    parameters:
      version:
        type: string
      latest:
        type: string
    steps:
      - common
      - run:
          name: Nagios Core+Web+Plugins
          command: |
            echo "Building for Nagios << parameters.version >> - Core + Web UI + Plugins"
            docker build --build-arg VERSION=<< parameters.version >> -t remie/docker-nagios:<< parameters.version >>-core-web-plugins ./core-web-plugins/Dockerfile

            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker push remie/docker-nagios:<< parameters.version >>
              docker push remie/docker-nagios:<< parameters.version >>-core-web-plugins
              if [ "<< parameters.latest >>" == "true" ]; then
                docker tag remie/docker-nagios:<< parameters.version >>-core-web-plugins remie/docker-nagios:latest
                docker push remie/docker-nagios:latest
              fi
            fi

            

workflows:
  version: 2
  deploy:
    jobs:
      - build-deploy:
          version: 4.3.0
      - build-deploy:
          version: 4.3.1
      - build-deploy:
          version: 4.3.2
      - build-deploy:
          version: 4.3.3
      - build-deploy:
          version: 4.3.4
      - build-deploy:
          version: 4.4.0
      - build-deploy:
          version: 4.4.1
      - build-deploy:
          version: 4.4.2
      - build-deploy:
          version: 4.4.3
      - build-deploy:
          version: 4.4.4
      - build-deploy:
          version: 4.4.5
          latest: "true"